version: '2'

services:
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./data/portainer_data:/data"

  nextgendb1:
    container_name: nextgendb1
    image: mysql:5.6
    command: mysqld --innodb-buffer-pool-size=20M
    volumes:
      - "./data/db1:/var/lib/mysql:rw"
    environment:
      - "MYSQL_DATABASE=mirthdb"
      - "MYSQL_USER=mirth"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=password"
    ports:
      - "3311:3306"

  nextgendb2:
    container_name: nextgendb2
    image: mysql:5.6
    command: mysqld --innodb-buffer-pool-size=20M
    volumes:
      - "./data/db2:/var/lib/mysql:rw"
    environment:
      - "MYSQL_DATABASE=mirthdb2"
      - "MYSQL_USER=mirth"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=password"
    ports:
      - "3312:3306"

  nextgen1:
    build: mirth-connect
    image: fabrom/mirth-connect
    container_name: nextgen1
    volumes:
      - "./mirth-connect/mirth.properties:/opt/mirth-connect/conf/mirth.properties:rw"
      - "./data/spool_nextgen/:/var/spool/mirth/:rw"
    ports:
      - "9091:8080"
      - "9441:8443"
    links:
      - nextgendb1
    depends_on:
      - nextgendb1

  nextgen2:
    build: mirth-connect
    image: fabrom/mirth-connect
    container_name: nextgen2
    volumes:
      - "./mirth-connect/mirth2.properties:/opt/mirth-connect/conf/mirth.properties:rw"
      - "./data/spool_nextgen2/:/var/spool/mirth/:rw"
    ports:
      - "9092:8081"
      - "9442:8444"
      - "6661:6661"
    links:
      - nextgendb2
      - nextgen1
    depends_on:
      - nextgendb2
      - nextgen1
